In [1]:
from sklearn.datasets import load_iris


In [3]:
x,y=load_iris(return_X_y=True)

In [4]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
from  sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [6]:
from sklearn.naive_bayes import GaussianNB
gb=GaussianNB()

In [8]:
gb.fit(x_train,y_train)

GaussianNB()

In [9]:
y_pred=gb.predict(x_test)

In [10]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
cm=confusion_matrix(y_test,y_pred)
score=accuracy_score(y_test,y_pred)
cr=classification_report(y_test,y_pred)
print(cm)
print(score)
print(cr)

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [11]:
import seaborn as sns 
df=sns.load_dataset("tips")
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [12]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [26]:
x=['total_bill', 'tip', 'sex', 'smoker', 'day']
y=['time']

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[x], df[y], test_size=0.42,random_state=0)


In [28]:
x_train

,total_bill,tip,sex,smoker,day
86,13.03,2.00,Male,No,Thur
10,10.27,1.71,Male,No,Sun
137,14.15,2.00,Female,No,Thur
173,31.85,3.18,Male,Yes,Sun
126,8.52,1.48,Male,No,Thur
...,...,...,...,...,...
67,3.07,1.00,Female,Yes,Sat
192,28.44,2.56,Male,Yes,Thur
117,10.65,1.50,Female,No,Thur
47,32.40,6.00,Male,No,Sun


In [29]:
x_test

,total_bill,tip,sex,smoker,day
64,17.59,2.64,Male,No,Sat
63,18.29,3.76,Male,Yes,Sat
55,19.49,3.51,Male,No,Sun
111,7.25,1.00,Female,No,Sat
225,16.27,2.50,Female,Yes,Fri
...,...,...,...,...,...
80,19.44,3.00,Male,Yes,Thur
51,10.29,2.60,Female,No,Sun
123,15.95,2.00,Male,No,Thur
201,12.74,2.01,Female,Yes,Thur


In [30]:
y_train

,time
86,Lunch
10,Dinner
137,Lunch
173,Dinner
126,Lunch
...,...
67,Dinner
192,Lunch
117,Lunch
47,Dinner


In [31]:
y_test

,time
64,Dinner
63,Dinner
55,Dinner
111,Dinner
225,Lunch
...,...
80,Lunch
51,Dinner
123,Lunch
201,Lunch


In [25]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()

In [42]:
print(x_train['sex'].unique())
print(x_test['sex'].unique())

[1 0]
['Male', 'Female']
Categories (2, object): ['Male', 'Female']


In [43]:
x_train['sex'] = x_train['sex'].map({'Male':1, 'Female':0})
x_test['sex'] = x_test['sex'].map({'Male':1, 'Female':0})

In [44]:
x_train['smoker'] = x_train['smoker'].map({'Yes':1, 'No':0})
x_test['smoker'] = x_test['smoker'].map({'Yes':1, 'No':0})

In [46]:
y_train['time'] = y_train['time'].map({'Lunch':0, 'Dinner':1})
y_test['time'] = y_test['time'].map({'Lunch':0, 'Dinner':1})

In [47]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


In [48]:
ct=ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),['day'])],remainder="passthrough")

In [49]:
ct.fit_transform(x_train)

array([[ 0.  ,  0.  ,  1.  , 13.03,  2.  ,   nan,   nan],
       [ 0.  ,  1.  ,  0.  , 10.27,  1.71,   nan,   nan],
       [ 0.  ,  0.  ,  1.  , 14.15,  2.  ,   nan,   nan],
       [ 0.  ,  1.  ,  0.  , 31.85,  3.18,   nan,   nan],
       [ 0.  ,  0.  ,  1.  ,  8.52,  1.48,   nan,   nan],
       [ 0.  ,  1.  ,  0.  , 17.46,  2.54,   nan,   nan],
       [ 0.  ,  1.  ,  0.  , 14.83,  3.02,   nan,   nan],
       [ 1.  ,  0.  ,  0.  , 12.69,  2.  ,   nan,   nan],
       [ 0.  ,  1.  ,  0.  , 12.54,  2.5 ,   nan,   nan],
       [ 0.  ,  0.  ,  0.  , 13.42,  3.48,   nan,   nan],
       [ 1.  ,  0.  ,  0.  , 17.92,  4.08,   nan,   nan],
       [ 0.  ,  1.  ,  0.  , 16.21,  2.  ,   nan,   nan],
       [ 0.  ,  1.  ,  0.  , 22.23,  5.  ,   nan,   nan],
       [ 0.  ,  1.  ,  0.  , 20.76,  2.24,   nan,   nan],
       [ 1.  ,  0.  ,  0.  , 29.03,  5.92,   nan,   nan],
       [ 0.  ,  1.  ,  0.  , 21.5 ,  3.5 ,   nan,   nan],
       [ 1.  ,  0.  ,  0.  , 50.81, 10.  ,   nan,   nan],
       [ 1.  ,

In [ ]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.impute import SimpleImputer
import numpy as np
bb=BernoulliNB()
# Impute missing values in x_train and x_test
imputer = SimpleImputer(strategy='mean')
x_train_imputed = imputer.fit_transform(x_train)
bb=BernoulliNB()
# Apply the column transformer to encode 'day' in x_train and x_test
x_train_encoded = ct.transform(x_train)
ct = ColumnTransformer(
    transformers=[('onehot', OneHotEncoder(drop='first', handle_unknown='ignore'), ['day'])],
    remainder="passthrough"
)
# Impute missing values in x_train_encoded and x_test_encoded
imputer = SimpleImputer(strategy='mean')
x_train_imputed = imputer.fit_transform(x_train_encoded)
bb=BernoulliNB()
# Impute missing values in x_train and x_test
imputer = SimpleImputer(strategy='mean')
x_train_imputed = imputer.fit_transform(x_train)
bb=BernoulliNB()
# Apply the column transformer to encode 'day' in x_train and x_test
x_train_encoded = ct.transform(x_train)
ct = ColumnTransformer(
    transformers=[('onehot', OneHotEncoder(drop='first', handle_unknown='ignore'), ['day'])],
    remainder="passthrough"
)
# Impute missing values in x_train_encoded and x_test_encoded
imputer = SimpleImputer(strategy='mean')
x_train_imputed = imputer.fit_transform(x_train_encoded)
x_test_encoded = ct.transform(x_test)
x_test_imputed = imputer.transform(x_test_encoded)

# Fill NaN in y_train and y_test with a mode or drop rows
y_train_filled = y_train.fillna(y_train.mode()[0])
y_test_filled = y_test.fillna(y_test.mode()[0])

bb.fit(x_train_imputed, y_train_filled.values.ravel())

# Fill NaN in y_train and y_test with a mode or drop rows
y_train_filled = y_train.fillna(y_train.mode()[0])
y_test_filled = y_test.fillna(y_test.mode()[0])

bb.fit(x_train_imputed, y_train_filled.values.ravel())

# Fill NaN in y_train and y_test with a mode or drop rows
y_train_filled = y_train.fillna(y_train.mode()[0])
y_test_filled = y_test.fillna(y_test.mode()[0])

bb.fit(x_train_imputed, y_train_filled.values.ravel())

# Fill NaN in y_train and y_test with a mode or drop rows
y_train_filled = y_train.fillna(y_train.mode()[0])
y_test_filled = y_test.fillna(y_test.mode()[0])

bb.fit(x_train_imputed, y_train_filled.values.ravel())

c:\Users\Asus\anaconda3\Lib\site-packages\sklearn\impute\_base.py:635: UserWarning: Skipping features without any observed values: ['sex' 'smoker']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(
c:\Users\Asus\anaconda3\Lib\site-packages\sklearn\impute\_base.py:635: UserWarning: Skipping features without any observed values: [5 6]. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(


NameError: name 'x_test_encoded' is not defined