In [32]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [34]:
#creating theone dimensional array
arr1=np.array([1,2,3,4,5,])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [35]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)


array([[1, 2, 3, 4, 5]])

In [36]:
# nested array
arr3=np.array([[1,2,3,4,5,],[5,9,7,8,9]])
print(arr3)

[[1 2 3 4 5]
 [5 9 7 8 9]]


In [37]:
arr3.shape

(2, 5)

In [38]:
#array with inbuilt function
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

In [39]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
print(arr3.ndim )# number of dimension 
print(arr3.size ) # number of element
print(arr3.dtype) # return the datatype of the array
print(arr3.itemsize) #return item size in bytes 4,8

2
10
int64
8


In [42]:
#numpy vectorized operation
# element vise addition
# element vise subtraction
# element vise multiplication
# element vise division
arr1=np.array([1,2,6,5,9])
arr2=np.array([5,8,9,7,9])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[ 6 10 15 12 18]
[-4 -6 -3 -2  0]
[ 5 16 54 35 81]
[0.2        0.25       0.66666667 0.71428571 1.        ]


In [43]:
# universal function 
arr=np.array([1,8,9,7,5])
print(np.sqrt(arr))

[1.         2.82842712 3.         2.64575131 2.23606798]


In [44]:
# exponential
print(np.exp(arr))

[2.71828183e+00 2.98095799e+03 8.10308393e+03 1.09663316e+03
 1.48413159e+02]


In [45]:
print(np.sin(arr))

[ 0.84147098  0.98935825  0.41211849  0.6569866  -0.95892427]


In [46]:
print(np.log(arr))

[0.         2.07944154 2.19722458 1.94591015 1.60943791]


In [48]:
# array slicing and indexing
arr1=np.array([[1,5,6,7,8],[6,8,7,9,4,],[5,9,7,6,4]])

In [49]:
print(arr1)

[[1 5 6 7 8]
 [6 8 7 9 4]
 [5 9 7 6 4]]


In [50]:
print(arr1[0])

[1 5 6 7 8]


In [53]:
print(arr1[1:, 2:4])

[[7 9]
 [7 6]]


In [57]:
# modifying the array element
arr1[0,0]=11
arr1[1:]=100


In [59]:
# mean and std deviation
data=np.array([1,5,6,7,8,9])
print(np.mean(data))


6.0


In [61]:
print(np.std(data))

2.581988897471611


In [4]:
# logivcal operation
data=np.array([5,8,3,7,9])
data >8

array([False, False, False, False,  True])