In [2]:
import pandas as pd
import nltk


In [3]:
messages = pd.read_csv(
    "SMSSpamCollection.txt",
    sep="\t",
    names=["label", "message"]
)

In [5]:
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [6]:
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords
ps=PorterStemmer()

In [7]:
import re
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus.append(review)

In [16]:
CV=CountVectorizer(max_features=2500,binary=True,ngram_range=(1,3))
x=CV.fit_transform(corpus).toarray()

In [13]:
import numpy as np
np.set_printoptions(edgeitems=30,linewidth=1000,formatter=dict(float=lambda x: f'{x:.3f}'))

In [14]:
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [15]:
x.shape

(5572, 2500)

In [17]:
CV=CountVectorizer(max_features=2500,binary=True,ngram_range=(1,3))
x=CV.fit_transform(corpus).toarray()

In [18]:
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [20]:
CV.vocabulary_

{'go': np.int64(816),
 'point': np.int64(1612),
 'crazi': np.int64(462),
 'avail': np.int64(113),
 'bugi': np.int64(218),
 'great': np.int64(867),
 'world': np.int64(2436),
 'la': np.int64(1072),
 'cine': np.int64(352),
 'got': np.int64(858),
 'wat': np.int64(2335),
 'ok': np.int64(1478),
 'lar': np.int64(1085),
 'joke': np.int64(1041),
 'wif': np.int64(2394),
 'free': np.int64(731),
 'entri': np.int64(623),
 'wkli': np.int64(2425),
 'comp': np.int64(403),
 'win': np.int64(2400),
 'cup': np.int64(478),
 'final': np.int64(695),
 'st': np.int64(1964),
 'may': np.int64(1265),
 'text': np.int64(2077),
 'receiv': np.int64(1707),
 'question': np.int64(1674),
 'std': np.int64(1980),
 'txt': np.int64(2194),
 'rate': np.int64(1687),
 'appli': np.int64(77),
 'free entri': np.int64(740),
 'entri wkli': np.int64(626),
 'std txt': np.int64(1981),
 'txt rate': np.int64(2202),
 'rate appli': np.int64(1688),
 'free entri wkli': np.int64(742),
 'std txt rate': np.int64(1982),
 'txt rate appli': np.int6

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=2500,binary=True,ngram_range=(1,3))
x=tfidf.fit_transform(corpus).toarray()

In [22]:
x

array([[0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, ..., 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, ..., 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000

In [23]:
tfidf.vocabulary_

{'go': np.int64(816),
 'point': np.int64(1612),
 'crazi': np.int64(462),
 'avail': np.int64(113),
 'bugi': np.int64(218),
 'great': np.int64(867),
 'world': np.int64(2436),
 'la': np.int64(1072),
 'cine': np.int64(352),
 'got': np.int64(858),
 'wat': np.int64(2335),
 'ok': np.int64(1478),
 'lar': np.int64(1085),
 'joke': np.int64(1041),
 'wif': np.int64(2394),
 'free': np.int64(731),
 'entri': np.int64(623),
 'wkli': np.int64(2425),
 'comp': np.int64(403),
 'win': np.int64(2400),
 'cup': np.int64(478),
 'final': np.int64(695),
 'st': np.int64(1964),
 'may': np.int64(1265),
 'text': np.int64(2077),
 'receiv': np.int64(1707),
 'question': np.int64(1674),
 'std': np.int64(1980),
 'txt': np.int64(2194),
 'rate': np.int64(1687),
 'appli': np.int64(77),
 'free entri': np.int64(740),
 'entri wkli': np.int64(626),
 'std txt': np.int64(1981),
 'txt rate': np.int64(2202),
 'rate appli': np.int64(1688),
 'free entri wkli': np.int64(742),
 'std txt rate': np.int64(1982),
 'txt rate appli': np.int6