In [1]:
import pandas as pd
import nltk


In [2]:
messages = pd.read_csv(
    "SMSSpamCollection.txt",
    sep="\t",
    names=["label", "message"]
)

In [3]:
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords
ps=PorterStemmer()

In [4]:
import re
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus.append(review)

In [7]:
CV=CountVectorizer(max_features=2500,binary=True,ngram_range=(1,2))
x=CV.fit_transform(corpus).toarray()

In [8]:
import numpy as np
np.set_printoptions(edgeitems=30,linewidth=1000,formatter=dict(float=lambda x: f'{x:.3f}'))

In [11]:
y=pd.get_dummies(messages['label'], drop_first=True)

In [17]:
y=y.iloc[:,0].values

In [19]:
from sklearn.model_selection import train_test_split
x_train,y_train,x_test,y_test=train_test_split(x,y,test_size=0.20,random_state=0)


In [21]:
from sklearn.naive_bayes import MultinomialNB
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=0)
span_detect_model = MultinomialNB().fit(x_train, y_train)
y_pred = span_detect_model.predict(x_test)
y_pred=span_detect_model.predict(x_test)

In [22]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.9865470852017937
              precision    recall  f1-score   support

       False       0.99      1.00      0.99       955
        True       0.98      0.93      0.95       160

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

[[952   3]
 [ 12 148]]


In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,binary=True,ngram_range=(1,2))

In [25]:
x=tv.fit_transform(corpus).toarray()

In [26]:
x

array([[0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, ..., 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, ..., 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000

In [27]:
Y=pd.get_dummies(messages['label'], drop_first=True)

In [28]:
Y=Y.iloc[:,0].values

In [29]:
from sklearn.model_selection import train_test_split
x_train,y_train,x_test,y_test=train_test_split(x,Y,test_size=0.20,random_state=0)


In [32]:
from sklearn.naive_bayes import MultinomialNB
x_train, x_test, y_train, y_test = train_test_split(
    x, Y, test_size=0.20, random_state=0
)
span_tdf_detect_model = MultinomialNB().fit(x_train, y_train)
y_pred=span_tdf_detect_model.predict(x_test)


In [33]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.9802690582959641
              precision    recall  f1-score   support

       False       0.98      1.00      0.99       955
        True       1.00      0.86      0.93       160

    accuracy                           0.98      1115
   macro avg       0.99      0.93      0.96      1115
weighted avg       0.98      0.98      0.98      1115

[[955   0]
 [ 22 138]]
